version: '3.1'

services:
  apache-php:
    build:
      context: ./dockerfiles
      dockerfile: apache-php
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nofile